[package]
name = "wordle"
version = "0.0.1"
description = "Wordle"
authors = ["hieudoanm <hieumdoan@gmail.com> (https://hieudoanm.github.io)"]
license = "GPT-3.0"
repository = "git+ssh://git@github.com/hieudoanm/wordle.git"
edition = "2021"
rust-version = "1.77.2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "=2.5.3" }

[dependencies]
serde_json = "=1.0.149"
serde = { version = "=1.0.228", features = ["derive"] }
log = "=0.4.29"
tauri = { version = "=2.9.5" }
tauri-plugin-log = "=2.8.0"
